// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Caml_chrome_debugger from "../../../node_modules/bs-platform/lib/es6/caml_chrome_debugger.js";

var list = /* :: */Caml_chrome_debugger.simpleVariant("::", [
    /* tuple */[
      "Oscillators",
      /* :: */Caml_chrome_debugger.simpleVariant("::", [
          "DRH-oscillators.rle",
          /* :: */Caml_chrome_debugger.simpleVariant("::", [
              "traffic-light-hasslers.rle",
              /* :: */Caml_chrome_debugger.simpleVariant("::", [
                  "unique-high-period.rle",
                  /* :: */Caml_chrome_debugger.simpleVariant("::", [
                      "honey-farm-hasslers.rle",
                      /* :: */Caml_chrome_debugger.simpleVariant("::", [
                          "low-period.rle",
                          /* :: */Caml_chrome_debugger.simpleVariant("::", [
                              "p138.rle",
                              /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                  "p103079214841.rle",
                                  /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                      "phase-shift.rle",
                                      /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                          "p59-glider-loop.lua",
                                          /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                              "billiard-table.rle",
                                              /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                  "extensible-low-period.rle",
                                                  /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                      "glider-stream-crystal.rle",
                                                      /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                          "queen-bee-turn.rle",
                                                          /* [] */0
                                                        ])
                                                    ])
                                                ])
                                            ])
                                        ])
                                    ])
                                ])
                            ])
                        ])
                    ])
                ])
            ])
        ])
    ],
    /* :: */Caml_chrome_debugger.simpleVariant("::", [
        /* tuple */[
          "Signal-Circuitry",
          /* :: */Caml_chrome_debugger.simpleVariant("::", [
              "heisenburp-46-natural.rle",
              /* :: */Caml_chrome_debugger.simpleVariant("::", [
                  "Unit-Life-Deep-Cell.rle",
                  /* :: */Caml_chrome_debugger.simpleVariant("::", [
                      "high-bandwidth-telegraph.rle.gz",
                      /* :: */Caml_chrome_debugger.simpleVariant("::", [
                          "traffic-lights-extruder.rle",
                          /* :: */Caml_chrome_debugger.simpleVariant("::", [
                              "h-to-h-collection-26Aug2017.zip",
                              /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                  "constructor-memory-tape.rle",
                                  /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                      "signal-turns-and-fizzles.rle.gz",
                                      /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                          "heisenblinker-30.rle",
                                          /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                              "reflectors2.rle",
                                              /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                  "constructor-memory-loop.rle",
                                                  /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                      "stargate.rle",
                                                      /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                          "heisenburp-30.rle",
                                                          /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                              "advancer.rle",
                                                              /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                  "Turing-Machine-3-state.rle",
                                                                  /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                      "heisenburp-46.rle",
                                                                      /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                          "chase-the-glider.rle",
                                                                          /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                              "p46racetrack.rle",
                                                                              /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                  "Unit-Life-Cell-512x512.rle",
                                                                                  /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                      "single-channel-spiral-growth.rle.gz",
                                                                                      /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                          "reflectors.rle",
                                                                                          /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                              "p30-racetrack.rle",
                                                                                              /* [] */0
                                                                                            ])
                                                                                        ])
                                                                                    ])
                                                                                ])
                                                                            ])
                                                                        ])
                                                                    ])
                                                                ])
                                                            ])
                                                        ])
                                                    ])
                                                ])
                                            ])
                                        ])
                                    ])
                                ])
                            ])
                        ])
                    ])
                ])
            ])
        ],
        /* :: */Caml_chrome_debugger.simpleVariant("::", [
            /* tuple */[
              "Guns",
              /* :: */Caml_chrome_debugger.simpleVariant("::", [
                  "7-in-a-row-Cordership-V-gun.rle",
                  /* :: */Caml_chrome_debugger.simpleVariant("::", [
                      "2c5-spaceship-gun-p690.rle",
                      /* :: */Caml_chrome_debugger.simpleVariant("::", [
                          "golly-ticker.rle",
                          /* :: */Caml_chrome_debugger.simpleVariant("::", [
                              "p690-PT-Cordership-gun.rle",
                              /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                  "pseudo-p34-gun.rle",
                                  /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                      "p59-gun-with-Snark-reflectors.rle",
                                      /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                          "2c5-spaceship-gun-p416.rle",
                                          /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                              "gun-p165mwss.rle",
                                              /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                  "loafer-gun-p210.rle",
                                                  /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                      "vacuum-cleaner.rle",
                                                      /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                          "Cordership-gun-p784.rle",
                                                          /* [] */0
                                                        ])
                                                    ])
                                                ])
                                            ])
                                        ])
                                    ])
                                ])
                            ])
                        ])
                    ])
                ])
            ],
            /* :: */Caml_chrome_debugger.simpleVariant("::", [
                /* tuple */[
                  "Miscellaneous",
                  /* :: */Caml_chrome_debugger.simpleVariant("::", [
                      "four-primers.rle.gz",
                      /* :: */Caml_chrome_debugger.simpleVariant("::", [
                          "lightspeed.rle",
                          /* :: */Caml_chrome_debugger.simpleVariant("::", [
                              "Calcyman-primer.zip",
                              /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                  "Cambrian-Explosion.rle",
                                  /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                      "loggrow-corder.rle",
                                      /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                          "infinity-hotel2.rle",
                                          /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                              "infinity-hotel0.rle",
                                              /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                  "wicks-DRH-2002.rle",
                                                  /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                      "infinity-hotel1.rle",
                                                      /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                          "twinprimes.rle",
                                                          /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                              "die658.rle",
                                                              /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                  "diagfuse1.rle",
                                                                  /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                      "blockstacker.rle",
                                                                      /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                          "fermat-primes.rle",
                                                                          /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                              "elbow-ladders.rle",
                                                                              /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                  "tubstretch-c124b.rle",
                                                                                  /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                      "infinity-hotel3.rle",
                                                                                      /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                          "sawtooth6b.rle",
                                                                                          /* [] */0
                                                                                        ])
                                                                                    ])
                                                                                ])
                                                                            ])
                                                                        ])
                                                                    ])
                                                                ])
                                                            ])
                                                        ])
                                                    ])
                                                ])
                                            ])
                                        ])
                                    ])
                                ])
                            ])
                        ])
                    ])
                ],
                /* :: */Caml_chrome_debugger.simpleVariant("::", [
                    /* tuple */[
                      "Rakes",
                      /* :: */Caml_chrome_debugger.simpleVariant("::", [
                          "c2-Cordership-rake.rle",
                          /* :: */Caml_chrome_debugger.simpleVariant("::", [
                              "basic-rakes.rle",
                              /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                  "p270-frothing-puffer-rake.rle",
                                  /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                      "2c5-engineless-rake-p185.rle",
                                      /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                          "weekender-distaff.rle.gz",
                                          /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                              "spider-rake.rle",
                                              /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                  "c5-adjustable-rake.rle",
                                                  /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                      "2c5-spaceship-rake-p240.rle",
                                                      /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                          "c4-sideways-rake.rle",
                                                          /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                              "c3-forward-rake-p333.rle",
                                                              /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                  "forward-LWSS-rake-p90.rle",
                                                                  /* [] */0
                                                                ])
                                                            ])
                                                        ])
                                                    ])
                                                ])
                                            ])
                                        ])
                                    ])
                                ])
                            ])
                        ])
                    ],
                    /* :: */Caml_chrome_debugger.simpleVariant("::", [
                        /* tuple */[
                          "Still-Lifes",
                          /* :: */Caml_chrome_debugger.simpleVariant("::", [
                              "eaters.rle",
                              /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                  "eaters-misc.rle",
                                  /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                      "ss-eaters.rle",
                                      /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                          "random.rle",
                                          /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                              "1998-eater-stamp-collection.rle",
                                              /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                  "stripey.rle",
                                                  /* [] */0
                                                ])
                                            ])
                                        ])
                                    ])
                                ])
                            ])
                        ],
                        /* :: */Caml_chrome_debugger.simpleVariant("::", [
                            /* tuple */[
                              "Breeders",
                              /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                  "rake-breeder.rle",
                                  /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                      "slide-breeder.rle",
                                      /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                          "switch-engine-ping-pong.rle",
                                          /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                              "breeder.lif",
                                              /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                  "pi-blink-breeder1.rle",
                                                  /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                      "c4-diag-switch-engines.rle",
                                                      /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                          "pi-blink-breeder2.rle",
                                                          /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                              "switch-engine-breeder.rle",
                                                              /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                  "p100-H-channel-breeder.rle",
                                                                  /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                      "switch-engine-breeder-MR.rle",
                                                                      /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                          "LWSS-breeder.rle",
                                                                          /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                              "p90-rake-factory.rle",
                                                                              /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                  "spacefiller.rle",
                                                                                  /* [] */0
                                                                                ])
                                                                            ])
                                                                        ])
                                                                    ])
                                                                ])
                                                            ])
                                                        ])
                                                    ])
                                                ])
                                            ])
                                        ])
                                    ])
                                ])
                            ],
                            /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                /* tuple */[
                                  "Puffers",
                                  /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                      "pi-fuse-puffer.rle",
                                      /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                          "p100-H-track-puffer.rle",
                                          /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                              "line-puffer-unstable.rle",
                                              /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                  "puffer-train.rle",
                                                  /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                      "zigzag-wickstretcher.rle",
                                                      /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                          "c4-diagonal-puffer.rle",
                                                          /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                              "line-puffer-superstable.rle",
                                                              /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                  "puffer-2c5.rle",
                                                                  /* [] */0
                                                                ])
                                                            ])
                                                        ])
                                                    ])
                                                ])
                                            ])
                                        ])
                                    ])
                                ],
                                /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                    /* tuple */[
                                      "Spaceships",
                                      /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                          "Corder-lineship.rle",
                                          /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                              "orthogonal.rle",
                                              /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                  "c3-orthogonal.rle",
                                                  /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                      "2c5-orthogonal.rle",
                                                      /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                          "short-thin.rle",
                                                          /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                              "spaceship-types.rle",
                                                              /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                  "c4-orthogonal.rle",
                                                                  /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                      "smallest-low-period.rle",
                                                                      /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                          "Cordership-LWSS-freeze-tag.rle",
                                                                          /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                              "Cordership-boat-burner.rle",
                                                                              /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                  "diagonal.rle",
                                                                                  /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                      "adjustable-Corder-lineship.rle",
                                                                                      /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                          "c4-diagonal.rle",
                                                                                          /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                              "corderships.rle",
                                                                                              /* [] */0
                                                                                            ])
                                                                                        ])
                                                                                    ])
                                                                                ])
                                                                            ])
                                                                        ])
                                                                    ])
                                                                ])
                                                            ])
                                                        ])
                                                    ])
                                                ])
                                            ])
                                        ])
                                    ],
                                    /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                        /* tuple */[
                                          "Bounded-Grids",
                                          /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                              "agar-p3.rle",
                                              /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                  "torus.rle",
                                                  /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                      "pulsars-in-tube.rle",
                                                      /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                          "sphere.rle",
                                                          /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                              "torus-with-shift.rle",
                                                              /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                  "herringbone-agar-p14.rle",
                                                                  /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                      "Klein-bottle.rle",
                                                                      /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                          "cross-surface.rle",
                                                                          /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                              "lightspeed-bubble.rle",
                                                                              /* [] */0
                                                                            ])
                                                                        ])
                                                                    ])
                                                                ])
                                                            ])
                                                        ])
                                                    ])
                                                ])
                                            ])
                                        ],
                                        /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                            /* tuple */[
                                              "Methuselahs",
                                              /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                  "lidka-predecessor.rle",
                                                  /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                      "natural-LWSS.rle",
                                                      /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                          "temp-pulsars-big-s.rle",
                                                          /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                              "rabbits.lif",
                                                              /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                  "rabbits-relation-17465.rle",
                                                                  /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                      "iwona.rle",
                                                                      /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                          "rabbits-relation-17423.rle",
                                                                          /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                              "ark1.rle",
                                                                              /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                  "ark2.rle",
                                                                                  /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                      "acorn.lif",
                                                                                      /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                          "blom.rle",
                                                                                          /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                              "justyna.rle",
                                                                                              /* [] */0
                                                                                            ])
                                                                                        ])
                                                                                    ])
                                                                                ])
                                                                            ])
                                                                        ])
                                                                    ])
                                                                ])
                                                            ])
                                                        ])
                                                    ])
                                                ])
                                            ],
                                            /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                /* tuple */[
                                                  "Syntheses",
                                                  /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                      "two-glider-collisions.rle",
                                                      /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                          "slow-salvo-MWSS-oscillator.rle.gz",
                                                          /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                              "make-p11.rle",
                                                              /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                  "slow-salvo-eater-recipes.rle",
                                                                  /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                      "life-integer-constructions.rle",
                                                                      /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                          "make-p18.rle",
                                                                          /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                              "109-still-lifes.rle",
                                                                              /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                  "29-still-lifes.rle",
                                                                                  /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                      "make-osc-p5-plus.rle",
                                                                                      /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                          "make-p33.rle",
                                                                                          /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                              "blockish-and-blockic-seeds.rle",
                                                                                              /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                  "syntheses-of-c2-spaceships.rle.gz",
                                                                                                  /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                      "oscillator-syntheses.rle",
                                                                                                      /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                          "make-harbor.rle",
                                                                                                          /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                              "make-osc-p4.rle",
                                                                                                              /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                                                                                  "make-osc-p3.rle",
                                                                                                                  /* [] */0
                                                                                                                ])
                                                                                                            ])
                                                                                                        ])
                                                                                                    ])
                                                                                                ])
                                                                                            ])
                                                                                        ])
                                                                                    ])
                                                                                ])
                                                                            ])
                                                                        ])
                                                                    ])
                                                                ])
                                                            ])
                                                        ])
                                                    ])
                                                ],
                                                /* [] */0
                                              ])
                                          ])
                                      ])
                                  ])
                              ])
                          ])
                      ])
                  ])
              ])
          ])
      ])
  ]);

export {
  list ,
  
}
/* No side effect */
