// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Caml_chrome_debugger from "../../../node_modules/bs-platform/lib/es6/caml_chrome_debugger.js";

function flip(param_0, param_1) {
  return /* Flip */Caml_chrome_debugger.variant("Flip", 0, [
            param_0,
            param_1
          ]);
}

function setBoard(param_0) {
  return /* SetBoard */Caml_chrome_debugger.variant("SetBoard", 1, [param_0]);
}

function setBoardFromSeed(param_0) {
  return /* SetBoardFromSeed */Caml_chrome_debugger.variant("SetBoardFromSeed", 2, [param_0]);
}

function addSeed(param_0, param_1) {
  return /* AddSeed */Caml_chrome_debugger.variant("AddSeed", 3, [
            param_0,
            param_1
          ]);
}

function setSize(param_0, param_1) {
  return /* SetSize */Caml_chrome_debugger.variant("SetSize", 4, [
            param_0,
            param_1
          ]);
}

function setRule(param_0) {
  return /* SetRule */Caml_chrome_debugger.variant("SetRule", 5, [param_0]);
}

function setBackend(param_0) {
  return /* SetBackend */Caml_chrome_debugger.variant("SetBackend", 6, [param_0]);
}

function setDirectory(param_0) {
  return /* SetDirectory */Caml_chrome_debugger.variant("SetDirectory", 7, [param_0]);
}

function $$fetch(param_0) {
  return /* Fetch */Caml_chrome_debugger.variant("Fetch", 8, [param_0]);
}

function keyPressed(param_0) {
  return /* KeyPressed */Caml_chrome_debugger.variant("KeyPressed", 9, [param_0]);
}

function lifeData(param_0) {
  return /* LifeData */Caml_chrome_debugger.variant("LifeData", 10, [param_0]);
}

var b3S23 = /* B3S23 */0;

var b36S23 = /* B36S23 */1;

var nothing = /* Nothing */0;

var reset = /* Reset */1;

var next = /* Next */2;

var previous = /* Previous */3;

var setAutoClamp = /* SetAutoClamp */4;

var setShowPattern = /* SetShowPattern */5;

var clamp = /* Clamp */6;

var rule_list = /* :: */Caml_chrome_debugger.simpleVariant("::", [
    /* tuple */[
      "B3S23",
      /* B3S23 */0,
      0
    ],
    /* :: */Caml_chrome_debugger.simpleVariant("::", [
        /* tuple */[
          "B36S23",
          /* B36S23 */1,
          1
        ],
        /* [] */0
      ])
  ]);

var backend_list = /* :: */Caml_chrome_debugger.simpleVariant("::", [
    /* tuple */[
      "Html",
      /* Html */0,
      0
    ],
    /* :: */Caml_chrome_debugger.simpleVariant("::", [
        /* tuple */[
          "Svg",
          /* Svg */1,
          1
        ],
        /* :: */Caml_chrome_debugger.simpleVariant("::", [
            /* tuple */[
              "Canvas",
              /* Canvas */2,
              2
            ],
            /* [] */0
          ])
      ])
  ]);

var seed_list = /* :: */Caml_chrome_debugger.simpleVariant("::", [
    /* tuple */[
      "Test",
      "test.rle"
    ],
    /* :: */Caml_chrome_debugger.simpleVariant("::", [
        /* tuple */[
          "Elephant",
          "elephant.rle"
        ],
        /* :: */Caml_chrome_debugger.simpleVariant("::", [
            /* tuple */[
              "UFO",
              "ufo.rle"
            ],
            /* :: */Caml_chrome_debugger.simpleVariant("::", [
                /* tuple */[
                  "Bob",
                  "bob.rle"
                ],
                /* [] */0
              ])
          ])
      ])
  ]);

var file_list = /* :: */Caml_chrome_debugger.simpleVariant("::", [
    /* tuple */[
      "Bounded-Grids",
      /* :: */Caml_chrome_debugger.simpleVariant("::", [
          "agar-p3",
          /* :: */Caml_chrome_debugger.simpleVariant("::", [
              "cross-surface",
              /* [] */0
            ])
        ])
    ],
    /* :: */Caml_chrome_debugger.simpleVariant("::", [
        /* tuple */[
          "Breeders",
          /* :: */Caml_chrome_debugger.simpleVariant("::", [
              "rake-breeder",
              /* [] */0
            ])
        ],
        /* :: */Caml_chrome_debugger.simpleVariant("::", [
            /* tuple */[
              "Oscillators",
              /* :: */Caml_chrome_debugger.simpleVariant("::", [
                  "billiard-table",
                  /* [] */0
                ])
            ],
            /* [] */0
          ])
      ])
  ]);

export {
  b3S23 ,
  b36S23 ,
  nothing ,
  reset ,
  flip ,
  next ,
  previous ,
  setBoard ,
  setBoardFromSeed ,
  addSeed ,
  setAutoClamp ,
  setSize ,
  setRule ,
  setBackend ,
  setDirectory ,
  setShowPattern ,
  $$fetch ,
  keyPressed ,
  clamp ,
  lifeData ,
  rule_list ,
  backend_list ,
  seed_list ,
  file_list ,
  
}
/* No side effect */
