// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Draw from "./draw.bs.js";
import * as List from "../../../node_modules/bs-platform/lib/es6/list.js";
import * as Vdom from "../../../node_modules/bucklescript-tea/lib/es6_global/src-ocaml/vdom.js";
import * as Global from "./global.bs.js";
import * as Matrix from "./matrix.bs.js";
import * as Tea_html from "../../../node_modules/bucklescript-tea/lib/es6_global/src-ocaml/tea_html.js";
import * as Caml_format from "../../../node_modules/bs-platform/lib/es6/caml_format.js";
import * as Caml_chrome_debugger from "../../../node_modules/bs-platform/lib/es6/caml_chrome_debugger.js";

function view_button(title, msg) {
  return Tea_html.button(undefined, undefined, /* :: */Caml_chrome_debugger.simpleVariant("::", [
                Tea_html.onClick(msg),
                /* :: */Caml_chrome_debugger.simpleVariant("::", [
                    Tea_html.class$prime("flex-1"),
                    /* [] */0
                  ])
              ]), /* :: */Caml_chrome_debugger.simpleVariant("::", [
                Tea_html.text(title),
                /* [] */0
              ]));
}

function view_link(title, msg) {
  return Tea_html.p(undefined, undefined, /* [] */0, /* :: */Caml_chrome_debugger.simpleVariant("::", [
                Tea_html.a(undefined, undefined, /* :: */Caml_chrome_debugger.simpleVariant("::", [
                        Tea_html.href("#"),
                        /* :: */Caml_chrome_debugger.simpleVariant("::", [
                            Tea_html.onClick(msg),
                            /* [] */0
                          ])
                      ]), /* :: */Caml_chrome_debugger.simpleVariant("::", [
                        Tea_html.text(title),
                        /* [] */0
                      ])),
                /* [] */0
              ]));
}

function seed_link(param) {
  return Tea_html.div(undefined, undefined, /* [] */0, /* :: */Caml_chrome_debugger.simpleVariant("::", [
                Tea_html.a(undefined, undefined, /* :: */Caml_chrome_debugger.simpleVariant("::", [
                        Tea_html.href("#"),
                        /* :: */Caml_chrome_debugger.simpleVariant("::", [
                            Tea_html.onClick(/* Fetch */Caml_chrome_debugger.variant("Fetch", 10, [param[1]])),
                            /* [] */0
                          ])
                      ]), /* :: */Caml_chrome_debugger.simpleVariant("::", [
                        Tea_html.text(param[0]),
                        /* [] */0
                      ])),
                /* [] */0
              ]));
}

function select_rule(model) {
  return Tea_html.div(undefined, undefined, /* :: */Caml_chrome_debugger.simpleVariant("::", [
                Tea_html.class$prime("dropdown"),
                /* [] */0
              ]), /* :: */Caml_chrome_debugger.simpleVariant("::", [
                Tea_html.button(undefined, undefined, /* :: */Caml_chrome_debugger.simpleVariant("::", [
                        Tea_html.class$prime("btn btn-secondary dropdown-toggle"),
                        /* :: */Caml_chrome_debugger.simpleVariant("::", [
                            Tea_html.type$prime("button"),
                            /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                Vdom.attribute("", "data-toggle", "dropdown"),
                                /* [] */0
                              ])
                          ])
                      ]), /* :: */Caml_chrome_debugger.simpleVariant("::", [
                        Tea_html.text("Rule"),
                        /* [] */0
                      ])),
                /* :: */Caml_chrome_debugger.simpleVariant("::", [
                    Tea_html.div(undefined, undefined, /* :: */Caml_chrome_debugger.simpleVariant("::", [
                            Tea_html.class$prime("dropdown menu"),
                            /* [] */0
                          ]), List.map((function (param) {
                                return Tea_html.a(undefined, undefined, /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                              Tea_html.class$prime("dropdown-item"),
                                              /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                  Tea_html.href("#"),
                                                  /* [] */0
                                                ])
                                            ]), /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                              Tea_html.text(param[0]),
                                              /* [] */0
                                            ]));
                              }), Global.rule_list)),
                    /* [] */0
                  ])
              ]));
}

function select_backend(model) {
  var backend_option = function (param) {
    return Tea_html.option$prime(undefined, undefined, /* :: */Caml_chrome_debugger.simpleVariant("::", [
                  Tea_html.value(String(param[2])),
                  /* :: */Caml_chrome_debugger.simpleVariant("::", [
                      Tea_html.Attributes.selected(model.backend === param[1]),
                      /* [] */0
                    ])
                ]), /* :: */Caml_chrome_debugger.simpleVariant("::", [
                  Tea_html.text(param[0]),
                  /* [] */0
                ]));
  };
  return Tea_html.select(undefined, undefined, /* :: */Caml_chrome_debugger.simpleVariant("::", [
                Tea_html.onChange(undefined, (function (v) {
                        var i = Caml_format.caml_int_of_string(v);
                        var match = List.find((function (param) {
                                return i === param[2];
                              }), Global.backend_list);
                        return /* SetBackend */Caml_chrome_debugger.variant("SetBackend", 8, [match[1]]);
                      })),
                /* [] */0
              ]), List.map(backend_option, Global.backend_list));
}

function params_form(model) {
  return Tea_html.div(undefined, undefined, /* :: */Caml_chrome_debugger.simpleVariant("::", [
                Tea_html.class$prime("flex"),
                /* [] */0
              ]), /* :: */Caml_chrome_debugger.simpleVariant("::", [
                select_rule(model),
                /* :: */Caml_chrome_debugger.simpleVariant("::", [
                    select_backend(model),
                    /* :: */Caml_chrome_debugger.simpleVariant("::", [
                        Tea_html.span(undefined, undefined, /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                Tea_html.class$prime("label-i"),
                                /* [] */0
                              ]), /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                Tea_html.text("x = "),
                                /* [] */0
                              ])),
                        /* :: */Caml_chrome_debugger.simpleVariant("::", [
                            Tea_html.input$prime(undefined, undefined, /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                    Tea_html.type$prime("text"),
                                    /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                        Tea_html.class$prime("small-i"),
                                        /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                            Tea_html.value(String(Matrix.width(model.board))),
                                            /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                Tea_html.onInput(undefined, (function (x) {
                                                        return /* Resize */Caml_chrome_debugger.variant("Resize", 4, [
                                                                  Caml_format.caml_int_of_string(x),
                                                                  Matrix.height(model.board)
                                                                ]);
                                                      })),
                                                /* [] */0
                                              ])
                                          ])
                                      ])
                                  ]), /* [] */0),
                            /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                Tea_html.span(undefined, undefined, /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                        Tea_html.class$prime("label-i"),
                                        /* [] */0
                                      ]), /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                        Tea_html.text("y = "),
                                        /* [] */0
                                      ])),
                                /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                    Tea_html.input$prime(undefined, undefined, /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                            Tea_html.type$prime("text"),
                                            /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                Tea_html.class$prime("small-i"),
                                                /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                    Tea_html.value(String(Matrix.height(model.board))),
                                                    /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                        Tea_html.onInput(undefined, (function (y) {
                                                                return /* Resize */Caml_chrome_debugger.variant("Resize", 4, [
                                                                          Matrix.width(model.board),
                                                                          Caml_format.caml_int_of_string(y)
                                                                        ]);
                                                              })),
                                                        /* [] */0
                                                      ])
                                                  ])
                                              ])
                                          ]), /* [] */0),
                                    /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                        view_button("Resize", /* Clamp */5),
                                        /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                            model.auto_clamp ? view_button("Auto: On", /* ToggleAutoClamp */4) : view_button("Auto: Off", /* ToggleAutoClamp */4),
                                            /* [] */0
                                          ])
                                      ])
                                  ])
                              ])
                          ])
                      ])
                  ])
              ]));
}

function view(model) {
  return Tea_html.div(undefined, undefined, /* :: */Caml_chrome_debugger.simpleVariant("::", [
                Tea_html.id("container"),
                /* :: */Caml_chrome_debugger.simpleVariant("::", [
                    Tea_html.class$prime("flex"),
                    /* [] */0
                  ])
              ]), /* :: */Caml_chrome_debugger.simpleVariant("::", [
                Tea_html.div(undefined, undefined, /* :: */Caml_chrome_debugger.simpleVariant("::", [
                        Tea_html.id("left-side"),
                        /* [] */0
                      ]), /* :: */Caml_chrome_debugger.simpleVariant("::", [
                        params_form(model),
                        /* :: */Caml_chrome_debugger.simpleVariant("::", [
                            Tea_html.div(undefined, undefined, /* [] */0, List.map(seed_link, Global.seed_list)),
                            /* [] */0
                          ])
                      ])),
                /* :: */Caml_chrome_debugger.simpleVariant("::", [
                    Tea_html.div(undefined, undefined, /* :: */Caml_chrome_debugger.simpleVariant("::", [
                            Tea_html.id("center"),
                            /* [] */0
                          ]), /* :: */Caml_chrome_debugger.simpleVariant("::", [
                            Tea_html.div(undefined, undefined, /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                    Tea_html.class$prime("board"),
                                    /* [] */0
                                  ]), Draw.draw(model)),
                            /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                Tea_html.div(undefined, undefined, /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                        Tea_html.class$prime("flex"),
                                        /* [] */0
                                      ]), /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                        view_button("Reset", /* Reset */1),
                                        /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                            view_button("Previous", /* Previous */3),
                                            /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                view_button("Next", /* Next */2),
                                                /* [] */0
                                              ])
                                          ])
                                      ])),
                                /* [] */0
                              ])
                          ])),
                    /* [] */0
                  ])
              ]));
}

export {
  view_button ,
  view_link ,
  seed_link ,
  select_rule ,
  select_backend ,
  params_form ,
  view ,
  
}
/* Draw Not a pure module */
