// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Draw from "./draw.bs.js";
import * as List from "../../../node_modules/bs-platform/lib/es6/list.js";
import * as Global from "./global.bs.js";
import * as Filelist from "./filelist.bs.js";
import * as Tea_html from "../../../node_modules/bucklescript-tea/lib/es6_global/src-ocaml/tea_html.js";
import * as Caml_format from "../../../node_modules/bs-platform/lib/es6/caml_format.js";
import * as Caml_chrome_debugger from "../../../node_modules/bs-platform/lib/es6/caml_chrome_debugger.js";

function view_button(title, msg) {
  return Tea_html.button(undefined, undefined, /* :: */Caml_chrome_debugger.simpleVariant("::", [
                Tea_html.onClick(msg),
                /* :: */Caml_chrome_debugger.simpleVariant("::", [
                    Tea_html.class$prime("btn btn-light flex-1"),
                    /* [] */0
                  ])
              ]), /* :: */Caml_chrome_debugger.simpleVariant("::", [
                Tea_html.text(title),
                /* [] */0
              ]));
}

function view_link(title, msg) {
  return Tea_html.p(undefined, undefined, /* [] */0, /* :: */Caml_chrome_debugger.simpleVariant("::", [
                Tea_html.a(undefined, undefined, /* :: */Caml_chrome_debugger.simpleVariant("::", [
                        Tea_html.href("#"),
                        /* :: */Caml_chrome_debugger.simpleVariant("::", [
                            Tea_html.onClick(msg),
                            /* [] */0
                          ])
                      ]), /* :: */Caml_chrome_debugger.simpleVariant("::", [
                        Tea_html.text(title),
                        /* [] */0
                      ])),
                /* [] */0
              ]));
}

function seed_link(param) {
  return Tea_html.div(undefined, undefined, /* [] */0, /* :: */Caml_chrome_debugger.simpleVariant("::", [
                Tea_html.a(undefined, undefined, /* :: */Caml_chrome_debugger.simpleVariant("::", [
                        Tea_html.href("#"),
                        /* :: */Caml_chrome_debugger.simpleVariant("::", [
                            Tea_html.onClick(/* Fetch */Caml_chrome_debugger.variant("Fetch", 8, [param[1]])),
                            /* [] */0
                          ])
                      ]), /* :: */Caml_chrome_debugger.simpleVariant("::", [
                        Tea_html.text(param[0]),
                        /* [] */0
                      ])),
                /* [] */0
              ]));
}

function auto_clamp_button(model) {
  var text = model.auto_clamp ? "Auto: On" : "Auto: Off";
  return view_button(text, /* SetAutoClamp */4);
}

function select_rule(model) {
  var rules_option = function (param) {
    var rule = param[1];
    return Tea_html.option$prime(undefined, undefined, /* :: */Caml_chrome_debugger.simpleVariant("::", [
                  Tea_html.value("dropdown-item"),
                  /* :: */Caml_chrome_debugger.simpleVariant("::", [
                      Tea_html.Attributes.selected(model.rule === rule),
                      /* :: */Caml_chrome_debugger.simpleVariant("::", [
                          Tea_html.onClick(/* SetRule */Caml_chrome_debugger.variant("SetRule", 5, [rule])),
                          /* [] */0
                        ])
                    ])
                ]), /* :: */Caml_chrome_debugger.simpleVariant("::", [
                  Tea_html.text(param[0]),
                  /* [] */0
                ]));
  };
  return Tea_html.select(undefined, undefined, /* [] */0, List.map(rules_option, Global.rule_list));
}

function select_backend(model) {
  var backend_option = function (param) {
    return Tea_html.option$prime(undefined, undefined, /* :: */Caml_chrome_debugger.simpleVariant("::", [
                  Tea_html.value(String(param[2])),
                  /* :: */Caml_chrome_debugger.simpleVariant("::", [
                      Tea_html.Attributes.selected(model.backend === param[1]),
                      /* [] */0
                    ])
                ]), /* :: */Caml_chrome_debugger.simpleVariant("::", [
                  Tea_html.text(param[0]),
                  /* [] */0
                ]));
  };
  return Tea_html.select(undefined, undefined, /* :: */Caml_chrome_debugger.simpleVariant("::", [
                Tea_html.onChange(undefined, (function (v) {
                        var i = Caml_format.caml_int_of_string(v);
                        var match = List.find((function (param) {
                                return i === param[2];
                              }), Global.backend_list);
                        return /* SetBackend */Caml_chrome_debugger.variant("SetBackend", 6, [match[1]]);
                      })),
                /* [] */0
              ]), List.map(backend_option, Global.backend_list));
}

function file_menu(model) {
  var directories = List.map((function (param) {
          return param[0];
        }), Filelist.list);
  var files_from_dir = function (dir) {
    try {
      return List.find((function (param) {
                      return dir === param[0];
                    }), Filelist.list)[1];
    }
    catch (exn){
      return /* [] */0;
    }
  };
  if (model.show_patterns) {
    return Tea_html.div(undefined, undefined, /* [] */0, /* :: */Caml_chrome_debugger.simpleVariant("::", [
                  Tea_html.div(undefined, undefined, /* :: */Caml_chrome_debugger.simpleVariant("::", [
                          Tea_html.class$prime("menu flex"),
                          /* [] */0
                        ]), List.map((function (e) {
                              return view_button(e, /* SetDirectory */Caml_chrome_debugger.variant("SetDirectory", 7, [e]));
                            }), directories)),
                  /* :: */Caml_chrome_debugger.simpleVariant("::", [
                      Tea_html.div(undefined, undefined, /* :: */Caml_chrome_debugger.simpleVariant("::", [
                              Tea_html.class$prime("menu flex"),
                              /* [] */0
                            ]), List.map((function (param) {
                                  var model$1 = model;
                                  var filename = param;
                                  return view_button(filename, /* Fetch */Caml_chrome_debugger.variant("Fetch", 8, ["Life/" + (model$1.directory + ("/" + filename))]));
                                }), files_from_dir(model.directory))),
                      /* [] */0
                    ])
                ]));
  } else {
    return Tea_html.div(undefined, undefined, /* [] */0, /* [] */0);
  }
}

function view(model) {
  return Tea_html.div(undefined, undefined, /* :: */Caml_chrome_debugger.simpleVariant("::", [
                Tea_html.id("container"),
                /* :: */Caml_chrome_debugger.simpleVariant("::", [
                    Tea_html.class$prime("flex"),
                    /* [] */0
                  ])
              ]), /* :: */Caml_chrome_debugger.simpleVariant("::", [
                Tea_html.div(undefined, undefined, /* :: */Caml_chrome_debugger.simpleVariant("::", [
                        Tea_html.id("center"),
                        /* [] */0
                      ]), /* :: */Caml_chrome_debugger.simpleVariant("::", [
                        Tea_html.div(undefined, undefined, /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                Tea_html.class$prime("menu flex"),
                                /* [] */0
                              ]), /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                view_button("Reset", /* Reset */1),
                                /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                    view_button("Next", /* Next */2),
                                    /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                        view_button("Previous", /* Previous */3),
                                        /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                            select_rule(model),
                                            /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                select_backend(model),
                                                /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                    view_button("Resize", /* Clamp */6),
                                                    /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                        auto_clamp_button(model),
                                                        /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                            view_button("Patterns", /* SetShowPattern */5),
                                                            /* [] */0
                                                          ])
                                                      ])
                                                  ])
                                              ])
                                          ])
                                      ])
                                  ])
                              ])),
                        /* :: */Caml_chrome_debugger.simpleVariant("::", [
                            file_menu(model),
                            /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                Tea_html.div(undefined, undefined, /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                        Tea_html.class$prime("board"),
                                        /* [] */0
                                      ]), Draw.draw(model)),
                                /* [] */0
                              ])
                          ])
                      ])),
                /* [] */0
              ]));
}

export {
  view_button ,
  view_link ,
  seed_link ,
  auto_clamp_button ,
  select_rule ,
  select_backend ,
  file_menu ,
  view ,
  
}
/* Draw Not a pure module */
