// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as List from "../node_modules/bs-platform/lib/es6/list.js";
import * as Global from "./global.bs.js";

function prune_top(_board) {
  while(true) {
    var board = _board;
    if (board) {
      if (List.exists((function (e) {
                return e === /* Alive */1;
              }), board[0])) {
        return board;
      } else {
        _board = board[1];
        continue ;
      }
    } else {
      return /* [] */0;
    }
  };
}

function prune_bottom(board) {
  return List.rev(prune_top(List.rev(board)));
}

function prune_left(_board) {
  while(true) {
    var board = _board;
    var column = List.map(List.hd, board);
    if (List.length(board) === 0) {
      return /* [] */0;
    } else if (List.exists((function (e) {
              return e === /* Alive */1;
            }), column)) {
      return board;
    } else {
      _board = List.map(List.tl, board);
      continue ;
    }
  };
}

function prune_right(board) {
  return List.map(List.rev, prune_left(List.map(List.rev, board)));
}

function prune(board) {
  var board$1 = prune_top(board);
  return prune_left(prune_right(List.rev(prune_top(List.rev(board$1)))));
}

function resize(board) {
  if (board === /* [] */0) {
    return /* :: */[
            /* :: */[
              /* Dead */0,
              /* [] */0
            ],
            /* [] */0
          ];
  } else {
    var board2 = List.map((function (row) {
            return /* :: */[
                    /* Dead */0,
                    List.append(row, /* :: */[
                          /* Dead */0,
                          /* [] */0
                        ])
                  ];
          }), board);
    var length = List.length(List.hd(board2));
    var column = List.init(length, (function (param) {
            return /* Dead */0;
          }));
    return /* :: */[
            column,
            List.append(board2, /* :: */[
                  column,
                  /* [] */0
                ])
          ];
  }
}

function clamp(board) {
  return resize(prune(board));
}

function next(board) {
  var is_alive = function (coords) {
    var j = coords[1];
    var i = coords[0];
    if (i < 0 || i >= List.length(board) || j < 0 || j >= List.length(List.hd(board))) {
      return 0;
    } else {
      var row = List.nth(board, i);
      var cell = List.nth(row, j);
      if (cell) {
        return 1;
      } else {
        return 0;
      }
    }
  };
  var sum_neighbourg = function (x, y) {
    var coords = List.map((function (coords) {
            return /* tuple */[
                    x + coords[0] | 0,
                    y + coords[1] | 0
                  ];
          }), /* :: */[
          /* tuple */[
            -1,
            -1
          ],
          /* :: */[
            /* tuple */[
              -1,
              0
            ],
            /* :: */[
              /* tuple */[
                -1,
                1
              ],
              /* :: */[
                /* tuple */[
                  0,
                  -1
                ],
                /* :: */[
                  /* tuple */[
                    0,
                    1
                  ],
                  /* :: */[
                    /* tuple */[
                      1,
                      -1
                    ],
                    /* :: */[
                      /* tuple */[
                        1,
                        0
                      ],
                      /* :: */[
                        /* tuple */[
                          1,
                          1
                        ],
                        /* [] */0
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]);
    var neighbourg = List.map(is_alive, coords);
    return List.fold_left((function (prim, prim$1) {
                  return prim + prim$1 | 0;
                }), 0, neighbourg);
  };
  var next_one = function (i, j, e) {
    var n = sum_neighbourg(i, j);
    if (e) {
      if (n === 3 || n === 2) {
        return /* Alive */1;
      } else {
        return /* Dead */0;
      }
    } else if (n !== 3) {
      return /* Dead */0;
    } else {
      return /* Alive */1;
    }
  };
  return Global.lmatrix_mapij(next_one, board);
}

function flip_if_equal(i, j, i2, j2, e) {
  if (i === i2 && j === j2) {
    if (e) {
      return /* Dead */0;
    } else {
      return /* Alive */1;
    }
  } else {
    return e;
  }
}

function flip(board, i, j) {
  return Global.lmatrix_mapij((function (param, param$1, param$2) {
                return flip_if_equal(i, j, param, param$1, param$2);
              }), board);
}

export {
  prune_top ,
  prune_bottom ,
  prune_left ,
  prune_right ,
  prune ,
  resize ,
  clamp ,
  next ,
  flip_if_equal ,
  flip ,
  
}
/* No side effect */
