// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as List from "../node_modules/bs-platform/lib/es6/list.js";
import * as Vdom from "../node_modules/bucklescript-tea/src-ocaml/vdom.js";
import * as $$Array from "../node_modules/bs-platform/lib/es6/array.js";
import * as Block from "../node_modules/bs-platform/lib/es6/block.js";
import * as Matrix from "./matrix.bs.js";
import * as Tea_svg from "../node_modules/bucklescript-tea/src-ocaml/tea_svg.js";
import * as Tea_html from "../node_modules/bucklescript-tea/src-ocaml/tea_html.js";

function draw_html(state) {
  var draw_line = function (i, line) {
    return Tea_html.div(undefined, undefined, /* :: */[
                Tea_html.class$prime("flex-1 flex"),
                /* [] */0
              ], $$Array.to_list($$Array.mapi((function (param, param$1) {
                          var i$1 = i;
                          var j = param;
                          var e = param$1;
                          return Tea_html.div(undefined, undefined, /* :: */[
                                      Tea_html.class$prime(e === /* Alive */1 ? "alive" : "dead"),
                                      /* :: */[
                                        Tea_html.onClick(/* Flip */Block.__(0, [
                                                i$1,
                                                j
                                              ])),
                                        /* [] */0
                                      ]
                                    ], /* [] */0);
                        }), line)));
  };
  return $$Array.to_list($$Array.mapi(draw_line, state.board));
}

function draw_svg(state) {
  var w = 600 / Matrix.width(state.board);
  var h = 600 / Matrix.height(state.board);
  var cells = Matrix.mapij((function (i, j, e) {
          var w$1 = w;
          var h$1 = h;
          var x = i * w;
          var y = j * h;
          var e$1 = e;
          return Tea_svg.node("rect", undefined, undefined, /* :: */[
                      Vdom.attribute("", "x", x.toPrecision(4)),
                      /* :: */[
                        Vdom.attribute("", "y", y.toPrecision(4)),
                        /* :: */[
                          Vdom.attribute("", "width", w$1.toPrecision(4)),
                          /* :: */[
                            Vdom.attribute("", "height", h$1.toPrecision(4)),
                            /* :: */[
                              Vdom.attribute("", "fill", e$1 === /* Alive */1 ? "black" : "white"),
                              /* [] */0
                            ]
                          ]
                        ]
                      ]
                    ], /* [] */0);
        }), state.board);
  return /* :: */[
          Tea_svg.svg(undefined, undefined, /* :: */[
                Vdom.attribute("", "width", "600"),
                /* :: */[
                  Vdom.attribute("", "height", "600"),
                  /* [] */0
                ]
              ], List.flatten($$Array.to_list($$Array.map($$Array.to_list, cells)))),
          /* [] */0
        ];
}

function draw_canvas(state) {
  return /* [] */0;
}

function draw(state) {
  var match = state.backend;
  switch (match) {
    case /* Html */0 :
        return draw_html(state);
    case /* Svg */1 :
        return draw_svg(state);
    case /* Canvas */2 :
        return /* [] */0;
    
  }
}

export {
  draw_html ,
  draw_svg ,
  draw_canvas ,
  draw ,
  
}
/* Tea_html Not a pure module */
