// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as $$Array from "../node_modules/bs-platform/lib/es6/array.js";
import * as Block from "../node_modules/bs-platform/lib/es6/block.js";
import * as Tea_html from "../node_modules/bucklescript-tea/src-ocaml/tea_html.js";

function draw(state) {
  return /* () */0;
}

function draw_html(state) {
  var draw_line = function (i, line) {
    return Tea_html.div(undefined, undefined, /* :: */[
                Tea_html.class$prime("flex-1 flex"),
                /* [] */0
              ], $$Array.to_list($$Array.mapi((function (param, param$1) {
                          var i$1 = i;
                          var j = param;
                          var e = param$1;
                          return Tea_html.div(undefined, undefined, /* :: */[
                                      Tea_html.class$prime(e === /* Alive */1 ? "alive" : "dead"),
                                      /* :: */[
                                        Tea_html.onClick(/* Click */Block.__(0, [
                                                i$1,
                                                j
                                              ])),
                                        /* [] */0
                                      ]
                                    ], /* [] */0);
                        }), line)));
  };
  return $$Array.to_list($$Array.mapi(draw_line, state.board));
}

export {
  draw ,
  draw_html ,
  
}
/* Tea_html Not a pure module */
