// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Global from "./global.bs.js";
import * as Caml_int32 from "../node_modules/bs-platform/lib/es6/caml_int32.js";
import * as Caml_primitive from "../node_modules/bs-platform/lib/es6/caml_primitive.js";

function draw_selection(x, y) {
  drawCircle(x, y, 20, "black");
  return /* () */0;
}

function draw(state) {
  var draw_one = function (i, j, e) {
    var dot_w = Caml_int32.div(canvas.width, state.size.contents.x);
    var dot_h = Caml_int32.div(canvas.height, state.size.contents.y);
    var r = Caml_primitive.caml_int_min(dot_w / 2 | 0, dot_h / 2 | 0);
    var x = Caml_int32.imul(i, dot_w) + (dot_w / 2 | 0) | 0;
    var y = Caml_int32.imul(j, dot_h) + (dot_h / 2 | 0) | 0;
    var match = e ? /* tuple */[
        "black",
        r / 2 | 0
      ] : /* tuple */[
        "grey",
        r / 5 | 0
      ];
    drawDisk(x, y, match[1], match[0]);
    return /* () */0;
  };
  clear();
  if (state.size.contents.x !== 0 && state.size.contents.y !== 0) {
    return Global.lmatrix_iterij(draw_one, state.board.contents);
  } else {
    return /* () */0;
  }
}

export {
  draw_selection ,
  draw ,
  
}
/* No side effect */
