// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as List from "../node_modules/bs-platform/lib/es6/list.js";
import * as $$Array from "../node_modules/bs-platform/lib/es6/array.js";
import * as Curry from "../node_modules/bs-platform/lib/es6/curry.js";

function matrix_mapij(f, a) {
  return $$Array.mapi((function (i, row) {
                return $$Array.mapi((function (j, e) {
                              return Curry._3(f, i, j, e);
                            }), row);
              }), a);
}

function matrix_iterij(f, a) {
  return $$Array.iteri((function (i, row) {
                return $$Array.iteri((function (j, e) {
                              return Curry._3(f, i, j, e);
                            }), row);
              }), a);
}

function lmatrix_mapij(f, a) {
  return List.mapi((function (i, row) {
                return List.mapi((function (j, e) {
                              return Curry._3(f, i, j, e);
                            }), row);
              }), a);
}

function lmatrix_iterij(f, a) {
  return List.iteri((function (i, row) {
                return List.iteri((function (j, e) {
                              return Curry._3(f, i, j, e);
                            }), row);
              }), a);
}

function lmatrix_create(i, j, e) {
  return List.init(i, (function (param) {
                return List.init(j, (function (param) {
                              return e;
                            }));
              }));
}

export {
  matrix_mapij ,
  matrix_iterij ,
  lmatrix_mapij ,
  lmatrix_iterij ,
  lmatrix_create ,
  
}
/* No side effect */
