// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Block from "../node_modules/bs-platform/lib/es6/block.js";

function flip(param_0, param_1) {
  return /* Flip */Block.__(0, [
            param_0,
            param_1
          ]);
}

function setBoard(param_0) {
  return /* SetBoard */Block.__(1, [param_0]);
}

function setBoardFromSeed(param_0) {
  return /* SetBoardFromSeed */Block.__(2, [param_0]);
}

function addSeed(param_0, param_1) {
  return /* AddSeed */Block.__(3, [
            param_0,
            param_1
          ]);
}

function resize(param_0, param_1) {
  return /* Resize */Block.__(4, [
            param_0,
            param_1
          ]);
}

function setX(param_0) {
  return /* SetX */Block.__(5, [param_0]);
}

function setY(param_0) {
  return /* SetY */Block.__(6, [param_0]);
}

function setRule(param_0) {
  return /* SetRule */Block.__(7, [param_0]);
}

function keyPressed(param_0) {
  return /* KeyPressed */Block.__(8, [param_0]);
}

function $$fetch(param_0) {
  return /* Fetch */Block.__(9, [param_0]);
}

function lifeData(param_0) {
  return /* LifeData */Block.__(10, [param_0]);
}

var b3S23 = /* B3S23 */0;

var b36S23 = /* B36S23 */1;

var nothing = /* Nothing */0;

var reset = /* Reset */1;

var next = /* Next */2;

var previous = /* Previous */3;

var toggleAutoClamp = /* ToggleAutoClamp */4;

var clamp = /* Clamp */5;

var rule_list = /* :: */[
  /* tuple */[
    "B3S23",
    /* B3S23 */0,
    0
  ],
  /* :: */[
    /* tuple */[
      "B36S23",
      /* B36S23 */1,
      1
    ],
    /* [] */0
  ]
];

var seed_list = /* :: */[
  /* tuple */[
    "Test",
    "test.rle"
  ],
  /* :: */[
    /* tuple */[
      "Elephant",
      "elephant.rle"
    ],
    /* :: */[
      /* tuple */[
        "UFO",
        "ufo.rle"
      ],
      /* :: */[
        /* tuple */[
          "Bob",
          "bob.rle"
        ],
        /* [] */0
      ]
    ]
  ]
];

export {
  b3S23 ,
  b36S23 ,
  nothing ,
  reset ,
  flip ,
  next ,
  previous ,
  setBoard ,
  setBoardFromSeed ,
  addSeed ,
  resize ,
  setX ,
  setY ,
  setRule ,
  keyPressed ,
  toggleAutoClamp ,
  clamp ,
  $$fetch ,
  lifeData ,
  rule_list ,
  seed_list ,
  
}
/* No side effect */
