// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as $$Array from "../node_modules/bs-platform/lib/es6/array.js";
import * as Curry from "../node_modules/bs-platform/lib/es6/curry.js";

function matrix_mapij(f, a) {
  return $$Array.mapi((function (i, row) {
                return $$Array.mapi((function (j, e) {
                              return Curry._3(f, i, j, e);
                            }), row);
              }), a);
}

function matrix_iterij(f, a) {
  return $$Array.iteri((function (i, row) {
                return $$Array.iteri((function (j, e) {
                              return Curry._3(f, i, j, e);
                            }), row);
              }), a);
}

export {
  matrix_mapij ,
  matrix_iterij ,
  
}
/* No side effect */
