// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Draw from "./draw.bs.js";
import * as List from "../node_modules/bs-platform/lib/es6/list.js";
import * as Block from "../node_modules/bs-platform/lib/es6/block.js";
import * as Board from "./board.bs.js";
import * as Curry from "../node_modules/bs-platform/lib/es6/curry.js";
import * as Global from "./global.bs.js";
import * as Printf from "../node_modules/bs-platform/lib/es6/printf.js";
import * as Tea_app from "../node_modules/bucklescript-tea/src-ocaml/tea_app.js";
import * as Keyboard from "./Keyboard.bs.js";
import * as Tea_html from "../node_modules/bucklescript-tea/src-ocaml/tea_html.js";
import * as Caml_format from "../node_modules/bs-platform/lib/es6/caml_format.js";

function init(param) {
  return /* tuple */[
          {
            size: {
              x: 3,
              y: 3
            },
            board: Global.lmatrix_create(3, 3, /* Dead */0),
            previous: /* [] */0,
            seeds: /* :: */[
              {
                name: "Glisseur 1",
                str: "[[0,1,0],[1,0,0],[1,1,1]]"
              },
              /* :: */[
                {
                  name: "Mathusalem 1",
                  str: "[[0,0,1,0],[0,1,0,0],[1,1,1,0]]"
                },
                /* [] */0
              ]
            ]
          },
          /* NoCmd */0
        ];
}

function update(state, $$event) {
  var board = Board.update(state, $$event);
  var previous;
  var exit = 0;
  if (typeof $$event === "number") {
    switch ($$event) {
      case /* Next */1 :
          previous = /* :: */[
            state.board,
            state.previous
          ];
          break;
      case /* Previous */2 :
          var match = state.previous;
          previous = match ? match[1] : /* [] */0;
          break;
      default:
        previous = state.previous;
    }
  } else {
    switch ($$event.tag | 0) {
      case /* Click */0 :
      case /* ClickThenNext */1 :
      case /* SetBoard */3 :
          exit = 1;
          break;
      default:
        previous = state.previous;
    }
  }
  if (exit === 1) {
    previous = /* :: */[
      state.board,
      state.previous
    ];
  }
  var seeds;
  seeds = typeof $$event === "number" || $$event.tag !== /* AddSeed */5 ? state.seeds : /* :: */[
      {
        name: $$event[0],
        str: $$event[1]
      },
      state.seeds
    ];
  var size_x = List.length(board);
  var size_y = List.length(board) === 0 ? 0 : List.length(List.hd(board));
  var size = {
    x: size_x,
    y: size_y
  };
  return /* tuple */[
          {
            size: size,
            board: board,
            previous: previous,
            seeds: seeds
          },
          /* NoCmd */0
        ];
}

function view_button(title, msg) {
  return Tea_html.button(undefined, undefined, /* :: */[
              Tea_html.onClick(msg),
              /* :: */[
                Tea_html.class$prime("flex-1"),
                /* [] */0
              ]
            ], /* :: */[
              Tea_html.text(title),
              /* [] */0
            ]);
}

function view_link(title, msg) {
  return Tea_html.p(undefined, undefined, /* [] */0, /* :: */[
              Tea_html.a(undefined, undefined, /* :: */[
                    Tea_html.href("#"),
                    /* :: */[
                      Tea_html.onClick(msg),
                      /* [] */0
                    ]
                  ], /* :: */[
                    Tea_html.text(title),
                    /* [] */0
                  ]),
              /* [] */0
            ]);
}

function view(model) {
  return Tea_html.div(undefined, undefined, /* :: */[
              Tea_html.id("container"),
              /* :: */[
                Tea_html.class$prime("flex"),
                /* [] */0
              ]
            ], /* :: */[
              Tea_html.div(undefined, undefined, /* :: */[
                    Tea_html.id("left-side"),
                    /* :: */[
                      Tea_html.class$prime("flex-1"),
                      /* [] */0
                    ]
                  ], List.map((function (s) {
                          return view_link(s.name, /* SetBoardFromSeed */Block.__(4, [s.str]));
                        }), model.seeds)),
              /* :: */[
                Tea_html.div(undefined, undefined, /* :: */[
                      Tea_html.id("center"),
                      /* :: */[
                        Tea_html.class$prime("flex-1"),
                        /* [] */0
                      ]
                    ], /* :: */[
                      Tea_html.div(undefined, undefined, /* :: */[
                            Tea_html.class$prime("flex"),
                            /* [] */0
                          ], /* :: */[
                            Tea_html.div(undefined, undefined, /* :: */[
                                  Tea_html.class$prime("flex-1 centered"),
                                  /* :: */[
                                    Tea_html.id("size"),
                                    /* [] */0
                                  ]
                                ], /* :: */[
                                  Tea_html.p(undefined, undefined, /* [] */0, /* :: */[
                                        Tea_html.text(Curry._2(Printf.sprintf(/* Format */[
                                                      /* String_literal */Block.__(11, [
                                                          "Size : ",
                                                          /* Int */Block.__(4, [
                                                              /* Int_d */0,
                                                              /* No_padding */0,
                                                              /* No_precision */0,
                                                              /* Char_literal */Block.__(12, [
                                                                  /* "x" */120,
                                                                  /* Int */Block.__(4, [
                                                                      /* Int_d */0,
                                                                      /* No_padding */0,
                                                                      /* No_precision */0,
                                                                      /* End_of_format */0
                                                                    ])
                                                                ])
                                                            ])
                                                        ]),
                                                      "Size : %dx%d"
                                                    ]), model.size.x, model.size.y)),
                                        /* [] */0
                                      ]),
                                  /* [] */0
                                ]),
                            /* :: */[
                              Tea_html.div(undefined, undefined, /* :: */[
                                    Tea_html.class$prime("flex-1 centered"),
                                    /* :: */[
                                      Tea_html.id("population"),
                                      /* [] */0
                                    ]
                                  ], /* :: */[
                                    Tea_html.p(undefined, undefined, /* [] */0, /* :: */[
                                          Tea_html.text("My Pop"),
                                          /* [] */0
                                        ]),
                                    /* [] */0
                                  ]),
                              /* [] */0
                            ]
                          ]),
                      /* :: */[
                        Tea_html.div(undefined, undefined, /* :: */[
                              Tea_html.class$prime("board"),
                              /* [] */0
                            ], Draw.draw_html(model)),
                        /* :: */[
                          Tea_html.div(undefined, undefined, /* :: */[
                                Tea_html.class$prime("flex"),
                                /* [] */0
                              ], /* :: */[
                                view_button("Reset", /* Reset */3),
                                /* :: */[
                                  view_button("Previous", /* Previous */2),
                                  /* :: */[
                                    view_button("Next", /* Next */1),
                                    /* [] */0
                                  ]
                                ]
                              ]),
                          /* [] */0
                        ]
                      ]
                    ]),
                /* :: */[
                  Tea_html.div(undefined, undefined, /* :: */[
                        Tea_html.id("right-side"),
                        /* :: */[
                          Tea_html.class$prime("flex-1"),
                          /* [] */0
                        ]
                      ], /* :: */[
                        Tea_html.div(undefined, undefined, /* :: */[
                              Tea_html.class$prime("flex"),
                              /* [] */0
                            ], /* :: */[
                              Tea_html.span(undefined, undefined, /* :: */[
                                    Tea_html.class$prime("flex-1"),
                                    /* [] */0
                                  ], /* :: */[
                                    Tea_html.text("x = "),
                                    /* [] */0
                                  ]),
                              /* :: */[
                                Tea_html.input$prime(undefined, undefined, /* :: */[
                                      Tea_html.class$prime("flex-1"),
                                      /* :: */[
                                        Tea_html.type$prime("text"),
                                        /* :: */[
                                          Tea_html.value(String(model.size.x)),
                                          /* :: */[
                                            Tea_html.onInput(undefined, (function (x) {
                                                    return /* SetX */Block.__(6, [Caml_format.caml_int_of_string(x)]);
                                                  })),
                                            /* [] */0
                                          ]
                                        ]
                                      ]
                                    ], /* [] */0),
                                /* :: */[
                                  Tea_html.span(undefined, undefined, /* :: */[
                                        Tea_html.class$prime("flex-1"),
                                        /* [] */0
                                      ], /* :: */[
                                        Tea_html.text("y = "),
                                        /* [] */0
                                      ]),
                                  /* :: */[
                                    Tea_html.input$prime(undefined, undefined, /* :: */[
                                          Tea_html.class$prime("flex-1"),
                                          /* :: */[
                                            Tea_html.type$prime("text"),
                                            /* :: */[
                                              Tea_html.value(String(model.size.y)),
                                              /* :: */[
                                                Tea_html.onInput(undefined, (function (y) {
                                                        return /* SetY */Block.__(7, [Caml_format.caml_int_of_string(y)]);
                                                      })),
                                                /* [] */0
                                              ]
                                            ]
                                          ]
                                        ], /* [] */0),
                                    /* [] */0
                                  ]
                                ]
                              ]
                            ]),
                        /* [] */0
                      ]),
                  /* [] */0
                ]
              ]
            ]);
}

function subscriptions(param) {
  return Keyboard.downs(undefined, (function (k) {
                return /* KeyPressed */Block.__(8, [k]);
              }));
}

function partial_arg_shutdown(param) {
  return /* NoCmd */0;
}

var partial_arg = {
  init: init,
  update: update,
  view: view,
  subscriptions: subscriptions,
  shutdown: partial_arg_shutdown
};

function main(param, param$1) {
  return Tea_app.program(partial_arg, param, param$1);
}

export {
  init ,
  update ,
  view_button ,
  view_link ,
  view ,
  subscriptions ,
  main ,
  
}
/* Draw Not a pure module */
