// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as $$Array from "../node_modules/bs-platform/lib/es6/array.js";
import * as Curry from "../node_modules/bs-platform/lib/es6/curry.js";

var make = $$Array.make_matrix;

function mapij(f, matrix) {
  return $$Array.mapi((function (i, row) {
                return $$Array.mapi((function (j, e) {
                              return Curry._3(f, i, j, e);
                            }), row);
              }), matrix);
}

export {
  make ,
  mapij ,
  
}
/* No side effect */
