// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Draw from "./draw.bs.js";
import * as List from "../node_modules/bs-platform/lib/es6/list.js";
import * as Block from "../node_modules/bs-platform/lib/es6/block.js";
import * as Curry from "../node_modules/bs-platform/lib/es6/curry.js";
import * as Matrix from "./matrix.bs.js";
import * as Printf from "../node_modules/bs-platform/lib/es6/printf.js";
import * as Tea_html from "../node_modules/bucklescript-tea/src-ocaml/tea_html.js";
import * as Caml_format from "../node_modules/bs-platform/lib/es6/caml_format.js";

function view_button(title, msg) {
  return Tea_html.button(undefined, undefined, /* :: */[
              Tea_html.onClick(msg),
              /* :: */[
                Tea_html.class$prime("flex-1"),
                /* [] */0
              ]
            ], /* :: */[
              Tea_html.text(title),
              /* [] */0
            ]);
}

function view_link(title, msg) {
  return Tea_html.p(undefined, undefined, /* [] */0, /* :: */[
              Tea_html.a(undefined, undefined, /* :: */[
                    Tea_html.href("#"),
                    /* :: */[
                      Tea_html.onClick(msg),
                      /* [] */0
                    ]
                  ], /* :: */[
                    Tea_html.text(title),
                    /* [] */0
                  ]),
              /* [] */0
            ]);
}

function rules_select(model) {
  var rules = /* :: */[
    /* tuple */[
      "B3S23",
      /* B3S23 */0,
      0
    ],
    /* :: */[
      /* tuple */[
        "B36S23",
        /* B36S23 */1,
        1
      ],
      /* [] */0
    ]
  ];
  var change_rule = function (str) {
    var i = Caml_format.caml_int_of_string(str);
    var res = List.find((function (e) {
            return i === e[2];
          }), rules);
    return /* SetRule */Block.__(8, [res[1]]);
  };
  var rules_option = function (tuple) {
    return Tea_html.option$prime(undefined, undefined, /* :: */[
                Tea_html.value(String(tuple[2])),
                /* :: */[
                  Tea_html.Attributes.selected(model.rule === tuple[1]),
                  /* [] */0
                ]
              ], /* :: */[
                Tea_html.text(tuple[0]),
                /* [] */0
              ]);
  };
  return Tea_html.select(undefined, undefined, /* :: */[
              Tea_html.onChange(undefined, change_rule),
              /* [] */0
            ], List.map(rules_option, rules));
}

function view(model) {
  return Tea_html.div(undefined, undefined, /* :: */[
              Tea_html.id("container"),
              /* :: */[
                Tea_html.class$prime("flex"),
                /* [] */0
              ]
            ], /* :: */[
              Tea_html.div(undefined, undefined, /* :: */[
                    Tea_html.id("left-side"),
                    /* [] */0
                  ], /* :: */[
                    rules_select(model),
                    /* :: */[
                      Tea_html.div(undefined, undefined, /* [] */0, List.map((function (s) {
                                  return view_link(s.name, /* SetBoardFromSeed */Block.__(4, [s.str]));
                                }), model.seeds)),
                      /* :: */[
                        Tea_html.a(undefined, undefined, /* :: */[
                              Tea_html.href("#"),
                              /* :: */[
                                Tea_html.onClick(/* Fetch */Block.__(10, ["test.rle"])),
                                /* [] */0
                              ]
                            ], /* :: */[
                              Tea_html.text("Hello"),
                              /* [] */0
                            ]),
                        /* :: */[
                          Tea_html.a(undefined, undefined, /* :: */[
                                Tea_html.href("#"),
                                /* :: */[
                                  Tea_html.onClick(/* Fetch */Block.__(10, ["elephant.rle"])),
                                  /* [] */0
                                ]
                              ], /* :: */[
                                Tea_html.text("Elephant"),
                                /* [] */0
                              ]),
                          /* :: */[
                            Tea_html.div(undefined, undefined, /* [] */0, /* :: */[
                                  Tea_html.span(undefined, undefined, /* [] */0, /* :: */[
                                        Tea_html.text("x = "),
                                        /* [] */0
                                      ]),
                                  /* :: */[
                                    Tea_html.input$prime(undefined, undefined, /* :: */[
                                          Tea_html.type$prime("text"),
                                          /* :: */[
                                            Tea_html.class$prime("small-i"),
                                            /* :: */[
                                              Tea_html.value(String(Matrix.width(model.board))),
                                              /* :: */[
                                                Tea_html.onInput(undefined, (function (x) {
                                                        return /* SetX */Block.__(6, [Caml_format.caml_int_of_string(x)]);
                                                      })),
                                                /* [] */0
                                              ]
                                            ]
                                          ]
                                        ], /* [] */0),
                                    /* :: */[
                                      Tea_html.span(undefined, undefined, /* [] */0, /* :: */[
                                            Tea_html.text("y = "),
                                            /* [] */0
                                          ]),
                                      /* :: */[
                                        Tea_html.input$prime(undefined, undefined, /* :: */[
                                              Tea_html.type$prime("text"),
                                              /* :: */[
                                                Tea_html.class$prime("small-i"),
                                                /* :: */[
                                                  Tea_html.value(String(Matrix.height(model.board))),
                                                  /* :: */[
                                                    Tea_html.onInput(undefined, (function (y) {
                                                            return /* SetY */Block.__(7, [Caml_format.caml_int_of_string(y)]);
                                                          })),
                                                    /* [] */0
                                                  ]
                                                ]
                                              ]
                                            ], /* [] */0),
                                        /* :: */[
                                          view_button("Clamp", /* Clamp */4),
                                          /* [] */0
                                        ]
                                      ]
                                    ]
                                  ]
                                ]),
                            /* :: */[
                              Tea_html.div(undefined, undefined, /* :: */[
                                    Tea_html.class$prime("flex"),
                                    /* [] */0
                                  ], /* :: */[
                                    model.auto_clamp ? view_button("Auto clamp: On", /* ToggleAutoClamp */3) : view_button("Auto clamp: Off", /* ToggleAutoClamp */3),
                                    /* [] */0
                                  ]),
                              /* [] */0
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]),
              /* :: */[
                Tea_html.div(undefined, undefined, /* :: */[
                      Tea_html.id("center"),
                      /* [] */0
                    ], /* :: */[
                      Tea_html.div(undefined, undefined, /* :: */[
                            Tea_html.class$prime("flex"),
                            /* [] */0
                          ], /* :: */[
                            Tea_html.div(undefined, undefined, /* :: */[
                                  Tea_html.class$prime("flex-1 centered"),
                                  /* :: */[
                                    Tea_html.id("size"),
                                    /* [] */0
                                  ]
                                ], /* :: */[
                                  Tea_html.p(undefined, undefined, /* [] */0, /* :: */[
                                        Tea_html.text(Curry._2(Printf.sprintf(/* Format */[
                                                      /* String_literal */Block.__(11, [
                                                          "Size : ",
                                                          /* Int */Block.__(4, [
                                                              /* Int_d */0,
                                                              /* No_padding */0,
                                                              /* No_precision */0,
                                                              /* Char_literal */Block.__(12, [
                                                                  /* "x" */120,
                                                                  /* Int */Block.__(4, [
                                                                      /* Int_d */0,
                                                                      /* No_padding */0,
                                                                      /* No_precision */0,
                                                                      /* End_of_format */0
                                                                    ])
                                                                ])
                                                            ])
                                                        ]),
                                                      "Size : %dx%d"
                                                    ]), Matrix.width(model.board), Matrix.height(model.board))),
                                        /* [] */0
                                      ]),
                                  /* [] */0
                                ]),
                            /* :: */[
                              Tea_html.div(undefined, undefined, /* :: */[
                                    Tea_html.class$prime("flex-1 centered"),
                                    /* :: */[
                                      Tea_html.id("population"),
                                      /* [] */0
                                    ]
                                  ], /* :: */[
                                    Tea_html.p(undefined, undefined, /* [] */0, /* :: */[
                                          Tea_html.text("My Pop"),
                                          /* [] */0
                                        ]),
                                    /* [] */0
                                  ]),
                              /* [] */0
                            ]
                          ]),
                      /* :: */[
                        Tea_html.div(undefined, undefined, /* :: */[
                              Tea_html.class$prime("board"),
                              /* [] */0
                            ], Draw.draw_html(model)),
                        /* :: */[
                          Tea_html.div(undefined, undefined, /* :: */[
                                Tea_html.class$prime("flex"),
                                /* [] */0
                              ], /* :: */[
                                view_button("Reset", /* Reset */5),
                                /* :: */[
                                  view_button("Previous", /* Previous */2),
                                  /* :: */[
                                    view_button("Next", /* Next */1),
                                    /* [] */0
                                  ]
                                ]
                              ]),
                          /* [] */0
                        ]
                      ]
                    ]),
                /* [] */0
              ]
            ]);
}

export {
  view_button ,
  view_link ,
  rules_select ,
  view ,
  
}
/* Draw Not a pure module */
