// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Draw from "./draw.bs.js";
import * as List from "../node_modules/bs-platform/lib/es6/list.js";
import * as Block from "../node_modules/bs-platform/lib/es6/block.js";
import * as Global from "./global.bs.js";
import * as Matrix from "./matrix.bs.js";
import * as Tea_html from "../node_modules/bucklescript-tea/src-ocaml/tea_html.js";
import * as Caml_format from "../node_modules/bs-platform/lib/es6/caml_format.js";

function view_button(title, msg) {
  return Tea_html.button(undefined, undefined, /* :: */[
              Tea_html.onClick(msg),
              /* :: */[
                Tea_html.class$prime("flex-1"),
                /* [] */0
              ]
            ], /* :: */[
              Tea_html.text(title),
              /* [] */0
            ]);
}

function view_link(title, msg) {
  return Tea_html.p(undefined, undefined, /* [] */0, /* :: */[
              Tea_html.a(undefined, undefined, /* :: */[
                    Tea_html.href("#"),
                    /* :: */[
                      Tea_html.onClick(msg),
                      /* [] */0
                    ]
                  ], /* :: */[
                    Tea_html.text(title),
                    /* [] */0
                  ]),
              /* [] */0
            ]);
}

function seed_link(param) {
  return Tea_html.div(undefined, undefined, /* [] */0, /* :: */[
              Tea_html.a(undefined, undefined, /* :: */[
                    Tea_html.href("#"),
                    /* :: */[
                      Tea_html.onClick(/* Fetch */Block.__(10, [param[1]])),
                      /* [] */0
                    ]
                  ], /* :: */[
                    Tea_html.text(param[0]),
                    /* [] */0
                  ]),
              /* [] */0
            ]);
}

function select_rule(model) {
  var rules_option = function (param) {
    return Tea_html.option$prime(undefined, undefined, /* :: */[
                Tea_html.value(String(param[2])),
                /* :: */[
                  Tea_html.Attributes.selected(model.rule === param[1]),
                  /* [] */0
                ]
              ], /* :: */[
                Tea_html.text(param[0]),
                /* [] */0
              ]);
  };
  return Tea_html.select(undefined, undefined, /* :: */[
              Tea_html.onChange(undefined, (function (v) {
                      var i = Caml_format.caml_int_of_string(v);
                      var match = List.find((function (param) {
                              return i === param[2];
                            }), Global.rule_list);
                      return /* SetRule */Block.__(7, [match[1]]);
                    })),
              /* [] */0
            ], List.map(rules_option, Global.rule_list));
}

function select_backend(model) {
  var backend_option = function (param) {
    return Tea_html.option$prime(undefined, undefined, /* :: */[
                Tea_html.value(String(param[2])),
                /* :: */[
                  Tea_html.Attributes.selected(model.backend === param[1]),
                  /* [] */0
                ]
              ], /* :: */[
                Tea_html.text(param[0]),
                /* [] */0
              ]);
  };
  return Tea_html.select(undefined, undefined, /* :: */[
              Tea_html.onChange(undefined, (function (v) {
                      var i = Caml_format.caml_int_of_string(v);
                      var match = List.find((function (param) {
                              return i === param[2];
                            }), Global.backend_list);
                      return /* SetBackend */Block.__(8, [match[1]]);
                    })),
              /* [] */0
            ], List.map(backend_option, Global.backend_list));
}

function params_form(model) {
  return Tea_html.div(undefined, undefined, /* :: */[
              Tea_html.class$prime("flex"),
              /* [] */0
            ], /* :: */[
              select_rule(model),
              /* :: */[
                select_backend(model),
                /* :: */[
                  Tea_html.span(undefined, undefined, /* :: */[
                        Tea_html.class$prime("label-i"),
                        /* [] */0
                      ], /* :: */[
                        Tea_html.text("x = "),
                        /* [] */0
                      ]),
                  /* :: */[
                    Tea_html.input$prime(undefined, undefined, /* :: */[
                          Tea_html.type$prime("text"),
                          /* :: */[
                            Tea_html.class$prime("small-i"),
                            /* :: */[
                              Tea_html.value(String(Matrix.width(model.board))),
                              /* :: */[
                                Tea_html.onInput(undefined, (function (x) {
                                        return /* Resize */Block.__(4, [
                                                  Caml_format.caml_int_of_string(x),
                                                  Matrix.height(model.board)
                                                ]);
                                      })),
                                /* [] */0
                              ]
                            ]
                          ]
                        ], /* [] */0),
                    /* :: */[
                      Tea_html.span(undefined, undefined, /* :: */[
                            Tea_html.class$prime("label-i"),
                            /* [] */0
                          ], /* :: */[
                            Tea_html.text("y = "),
                            /* [] */0
                          ]),
                      /* :: */[
                        Tea_html.input$prime(undefined, undefined, /* :: */[
                              Tea_html.type$prime("text"),
                              /* :: */[
                                Tea_html.class$prime("small-i"),
                                /* :: */[
                                  Tea_html.value(String(Matrix.height(model.board))),
                                  /* :: */[
                                    Tea_html.onInput(undefined, (function (y) {
                                            return /* Resize */Block.__(4, [
                                                      Matrix.width(model.board),
                                                      Caml_format.caml_int_of_string(y)
                                                    ]);
                                          })),
                                    /* [] */0
                                  ]
                                ]
                              ]
                            ], /* [] */0),
                        /* :: */[
                          view_button("Resize", /* Clamp */5),
                          /* :: */[
                            model.auto_clamp ? view_button("Auto: On", /* ToggleAutoClamp */4) : view_button("Auto: Off", /* ToggleAutoClamp */4),
                            /* [] */0
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]);
}

function view(model) {
  return Tea_html.div(undefined, undefined, /* :: */[
              Tea_html.id("container"),
              /* :: */[
                Tea_html.class$prime("flex"),
                /* [] */0
              ]
            ], /* :: */[
              Tea_html.div(undefined, undefined, /* :: */[
                    Tea_html.id("left-side"),
                    /* [] */0
                  ], /* :: */[
                    params_form(model),
                    /* :: */[
                      Tea_html.div(undefined, undefined, /* [] */0, List.map(seed_link, Global.seed_list)),
                      /* [] */0
                    ]
                  ]),
              /* :: */[
                Tea_html.div(undefined, undefined, /* :: */[
                      Tea_html.id("center"),
                      /* [] */0
                    ], /* :: */[
                      Tea_html.div(undefined, undefined, /* :: */[
                            Tea_html.class$prime("board"),
                            /* [] */0
                          ], Draw.draw(model)),
                      /* :: */[
                        Tea_html.div(undefined, undefined, /* :: */[
                              Tea_html.class$prime("flex"),
                              /* [] */0
                            ], /* :: */[
                              view_button("Reset", /* Reset */1),
                              /* :: */[
                                view_button("Previous", /* Previous */3),
                                /* :: */[
                                  view_button("Next", /* Next */2),
                                  /* [] */0
                                ]
                              ]
                            ]),
                        /* [] */0
                      ]
                    ]),
                /* [] */0
              ]
            ]);
}

export {
  view_button ,
  view_link ,
  seed_link ,
  select_rule ,
  select_backend ,
  params_form ,
  view ,
  
}
/* Draw Not a pure module */
